### ISSUE TITLE
编译报错，Error:(10, 8) 错误: 类Movieinfo是公共的, 应在名为 Movieinfo.java 的文件中声明

### ISSUE THREAD

**Issue by SusinDev** [ToryangChen/SampleDemo#3]
报错如题

**Comment by xuesongzh** [comment]
同遇到！怎么解决？

**Comment by ToryangChen** [comment]
Movieinfo这个类是以前写的，最后删掉了。可能某个类中有引用，删除对MovieInfo的引用即可！

**Comment by showdy** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.toryang.sampledemo.entities.usbox.UsBoxEntity.getSubjects()' on a null object reference
                                                                            at com.toryang.sampledemo.ui.adapter.OutRecyclerAdapter.onBindViewHolder(OutRecyclerAdapter.java:59)
                                                                            at com.toryang.sampledemo.ui.adapter.OutRecyclerAdapter.onBindViewHolder(OutRecyclerAdapter.java:28)

**Comment by kang3162611** [comment]
Movieinfo这个类引用太多了吧，删的烦死

**Comment by toryangchen** [comment]
这个问题其实很好解决，这是IDE造成的问题，我写的类名是 Movieinfo，对应的文件名也应该是Movieinfo.java。但是，不知道为什么IDE将文件名变成了movieinfo，导致类名和文件名不一样，就会出现这个问题；
解决方法：将movieinfo这个文件名改成Movieinfo即可；

**Comment by hezong001** [comment]
Error:Execution failed for task ':app:validateSigningDebug'.
> Keystore file F:\hz_FireFox_Download\SampleDemo-master\app\SampleDemo.jks not found for signing config 'release'.
我报这错误，SampleDemo.jks ，真机测试运行就报错了
